# SITE CONFIGURATION
baseurl: ""
url: "https://egel.github.io"

# THEME-SPECIFIC CONFIGURATION
title: The Egel's blog
description: "Maciej Sypień personal blog mainly about web development" # used by search engines
avatar: assets/img/triangle.svg
favicon: assets/6779124281580121298.svg
gravatar: 4d66c5a2d6be57e7cb9bdef200417b4d # Email MD5 hash

# Header and footer text
header_text: > #two or three lines to describe your site
  <h2>Simplicity and clarity of the implementation</h2>
  <p>An adventure through a digital network</p>
header_text_feature_image: assets/img/pexels/pexels-aleksandar-pasaric-2603464.jpg
footer_text: >
  Made with ♥ by Maciej Sypień since 2014 · All copyrights reserved.

# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: assets/img/lineart.png # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true # Enable if using math markup
mermaid: true # Enable mermaid-js for sequence and diagrams
google_analytics: "UA-115501084-1" # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false # To respect the usage of cookies
disqus_shortname: "egel"

# Colours, typography and padding
# Open the "_sass > base" folder, and open "_variables.scss"
google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
portfolio: true
search: false
tags: true

# PAGINATION
paginate: 7
paginate_path: "page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - .idea
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/node_modules
  - gemfiles/
  - node_modules/
  - type-on-strap.gemspec
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
